# Generated by Django 4.2.1 on 2023-05-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_categories_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
