# Generated by Django 4.2.1 on 2023-05-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_categories_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='img',
        ),
    ]
